# Generated by Django 5.2 on 2025-04-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('position', models.CharField(choices=[('Web Developer', 'Web Developer'), ('Software Engineer', 'Software Engineer'), ('Digital Marketing Executive', 'Digital Marketing Executive'), ('Cyber Security Analyst', 'Cyber Security Analyst'), ('HR Executive', 'HR Executive'), ('Graphic Designer', 'Graphic Designer')], max_length=50)),
                ('institution', models.CharField(max_length=100)),
                ('year_passing', models.CharField(max_length=4)),
                ('specialization', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('certifications', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('candidate_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(max_length=20)),
                ('interview_date', models.DateTimeField()),
                ('interviewer_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], max_length=20)),
                ('marks', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
            ],
        ),
    ]
