# Generated by Django 5.2 on 2025-04-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('interviewer_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], max_length=20)),
                ('marks', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='HRRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('interviewer_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], max_length=20)),
                ('marks', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('interviewer_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], max_length=20)),
                ('marks', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
            ],
        ),
        migrations.DeleteModel(
            name='InterviewRound',
        ),
    ]
