# Generated by Django 5.2 on 2025-04-06 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_resume_alter_candidate_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCandidateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('Web Developer', 'Web Developer'), ('Software Engineer', 'Software Engineer'), ('Digital Marketing Executive', 'Digital Marketing Executive'), ('Cyber Security Analyst', 'Cyber Security Analyst'), ('HR Executive', 'HR Executive'), ('Graphic Designer', 'Graphic Designer')], max_length=50, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('year_passing', models.CharField(blank=True, max_length=4, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
